version: '3.7'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  web:
    image: marcosrissotto/checkout-api
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
